package esyvendinggui;


import esyvendinggui.ErrorDialog;
import esyvendinggui.ObservableVals;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//package esyvendinggui;

/**
 *
 * @author Anon
 */
public class ChangeLogin extends javax.swing.JFrame {

    /**
     * Creates new form ChangeLogin
     */
    private ObservableVals systemObserver =null;
    private String username;
    private String password;
    private String confirm; 
    private String email;

    public String getConfirm() {
        return confirm;
    }

    public void setConfirm(String confirm) {
        this.confirm = confirm;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }
    private String phone;
    public ChangeLogin( ObservableVals systemObserver) {
        initComponents();
        this.systemObserver=systemObserver;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        usernameTextBox = new javax.swing.JTextField();
        passwordTextBox = new javax.swing.JTextField();
        confirmPasswdTextBox = new javax.swing.JTextField();
        emailTextBox = new javax.swing.JTextField();
        phoneTextBox = new javax.swing.JTextField();
        save = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setTitle("Change Login");
        jInternalFrame1.setVisible(true);

        jLabel1.setText("Username:");

        jLabel2.setText("Password:");

        jLabel3.setText("Confirm Password:");

        jLabel4.setText("Email:");

        jLabel5.setText("Phone:");

        usernameTextBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameTextBoxFocusLost(evt);
            }
        });

        passwordTextBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordTextBoxFocusLost(evt);
            }
        });

        confirmPasswdTextBox.setToolTipText("");
        confirmPasswdTextBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                confirmPasswdTextBoxFocusLost(evt);
            }
        });

        emailTextBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailTextBoxFocusLost(evt);
            }
        });

        phoneTextBox.setToolTipText("");
        phoneTextBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                phoneTextBoxFocusLost(evt);
            }
        });

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(save)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(confirmPasswdTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(72, 72, 72)
                        .addComponent(usernameTextBox))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(74, 74, 74)
                        .addComponent(passwordTextBox))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(101, 101, 101)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(emailTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(phoneTextBox))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(usernameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(passwordTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(confirmPasswdTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(emailTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(phoneTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(save)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrame1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        System.out.println("Still going here");
        if(this.getUsername()!=null && this.getPassword()!=null && this.getEmail()!=null && this.getPhone()!=null){
           System.out.println(this.getUsername()+" "+this.getPassword()+" "+this.getEmail()+" "+this.getPhone());
            if(this.getPassword().equals(this.getConfirm())){
               this.systemObserver.setChangeLoginListener(true);
            }
            else{
                 // check for correct email format
                 //   TODO HERE
                 ErrorDialog errMessage = new ErrorDialog();
                   errMessage.setMessage("Passwords dont Match");
                   errMessage.setMessage("Your passwords dont match");
                    java.awt.EventQueue.invokeLater(new Runnable() {
                      public void run() {
                          errMessage.setVisible(true);
                      }
                    });
            }
        }
        else{
            ErrorDialog errMessage = new ErrorDialog();
              errMessage.setMessage("All fields are required");
                   errMessage.setMessage("Please fill out all fields");
                    java.awt.EventQueue.invokeLater(new Runnable() {
                      public void run() {
                          errMessage.setVisible(true);
                      }
                    });
        }
    }//GEN-LAST:event_saveActionPerformed

    private void usernameTextBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameTextBoxFocusLost
        // TODO add your handling code here:
        //System.out.println(usernameTextBox.getText());
        this.setUsername(usernameTextBox.getText());
    }//GEN-LAST:event_usernameTextBoxFocusLost

    private void passwordTextBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordTextBoxFocusLost
        // TODO add your handling code here:
        this.setPassword(passwordTextBox.getText());
    }//GEN-LAST:event_passwordTextBoxFocusLost

    private void confirmPasswdTextBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirmPasswdTextBoxFocusLost
        // TODO add your handling code here:
        this.setConfirm(confirmPasswdTextBox.getText());
    }//GEN-LAST:event_confirmPasswdTextBoxFocusLost

    private void emailTextBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTextBoxFocusLost
        // TODO add your handling code here:
        this.setEmail(emailTextBox.getText());
    }//GEN-LAST:event_emailTextBoxFocusLost

    private void phoneTextBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneTextBoxFocusLost
        // TODO add your handling code here:
        this.setPhone(phoneTextBox.getText());
    }//GEN-LAST:event_phoneTextBoxFocusLost

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField confirmPasswdTextBox;
    private javax.swing.JTextField emailTextBox;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField passwordTextBox;
    private javax.swing.JTextField phoneTextBox;
    private javax.swing.JButton save;
    private javax.swing.JTextField usernameTextBox;
    // End of variables declaration//GEN-END:variables
}
