/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EV_GUI;


import javax.swing.JComboBox;
import javax.swing.JTextField;
import EV_BUSINESS.EV_OBSERVER.ObservableVals;

/**
 *
 * @author Anon
 */
public class BusinessSetUp extends javax.swing.JFrame {

    /**
     * Creates new form BusinessSetUp
     */
        private String productName ;
        private double price;
        private int slotID;
        private int quant; 
        private double tempRange; 
        private int currencyType; 
        private ObservableVals systemObserver =null;

    
    private boolean[]  ruleSet= new boolean [6];
    public boolean getRuleSet() {
        int ctr =0;
        for(int i = 0;i<6;i++){
         if (this.ruleSet[i]==true)
             ctr=ctr+1;
             System.out.println(ctr);
         }
         if(ctr == 6)
           return true;
         else
          return false;
    }
    public void setAvailableProductNames(String [] n){
        int len = n.length;
        for(int i=0;i<len;i++)
          this.products.addItem(n[i]);
         
    }
    public void setRuleSet(int index, boolean n) {
        this.ruleSet[index] = n;
    }
        
    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public int getSlotID() {
        return slotID;
    }

    public void setSlotID(int slotID) {
        this.slotID = slotID;
    }

    public int getQuant() {
        return quant;
    }

    public void setQuant(int quant) {
        this.quant = quant;
    }

    public double getTempRange() {
        return tempRange;
    }

    public void setTempRange(double tempRange) {
        this.tempRange = tempRange;
    }

    public int getCurrencyType() {
        return currencyType;
    }

    public void setCurrencyType(int currencyType) {
        this.currencyType = currencyType;
    }
        
  
    public BusinessSetUp(ObservableVals systemObserver) {
        initComponents();
        
        this.systemObserver = systemObserver;
    }
    public String[] getALL(){
     //PRODUCT_NAME,QUANTITY,PRICE,TEMP_RANGE,TEMP,CURRENCY_ID
     String [] returnVal= new String [8];
     //(ID,PRODUCT_NAME,QUANTITY,PRICE,TEMP_RANGE,TEMP,CURRENCY_ID)
      returnVal[0]="SLOT_CONFIG";
      returnVal[1]=""+this.getSlotID();
      returnVal[2]=""+this.getProductName();
      returnVal[3]=""+this.getQuant();
      returnVal[4]=""+this.getPrice();
      returnVal[5]=""+this.getTempRange();
      returnVal[6]="0.0";
      returnVal[7]=""+this.getCurrencyType();
     return returnVal;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        products = new javax.swing.JComboBox<>();
        productNameInput = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        slots = new javax.swing.JComboBox<>();
        prices = new javax.swing.JComboBox<>();
        quantity = new javax.swing.JComboBox<>();
        temRange = new javax.swing.JComboBox<>();
        currType = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        inputPrice = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setTitle("Business Setup");
        jInternalFrame1.setVisible(true);

        jLabel1.setText("Enter Product Name:");

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("X");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        products.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productsActionPerformed(evt);
            }
        });

        productNameInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                productNameInputFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(productNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(products, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(19, 19, 19))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(productNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(products, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        slots.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Slots:", "Slot 1", "Slot 2", "Slot 3", "Slot 4", "Slot 5", "Slot 6", "Slot 7", "Slot 8", "Slot 9", "Slot 10", "Slot 11", "Slot 12", "Slot 13", "Slot 14", "Slot 15", "Slot 16", "Slot 17", "Slot 18", "Slot 19", "Slot 20" }));
        slots.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slotsActionPerformed(evt);
            }
        });

        prices.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Price", "0.50", "1.00", "1.10", "1.20", "1.30", "1.40", "1.50", "1.60", "1.80", "2.00", "2.10", "2.20", "2.30", "2.40", "2.50", "2.60", "2.70", "2.80", "2.90", "3.00", "3.10", "3.20", "3.30", "3.40", "3.50", "3.60", "3.70", "3.80", "3.90", "4.00", "4.10", "4.20", "4.30", "4.40", "4.50", "4.60", "4.70", "4.80", "4.90", "5.00" }));
        prices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pricesActionPerformed(evt);
            }
        });

        quantity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quantity:", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));
        quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityActionPerformed(evt);
            }
        });

        temRange.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Temperature Range:", "N/A", "2-5 ,    degr Celsius", "6-10,   degr Celsius", "15-20, degr Celsius", "30-40, degr Celsius", "50-60, degr Celsius", "70-80, degr Celsius", "80-90, degr Celsius" }));
        temRange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temRangeActionPerformed(evt);
            }
        });

        currType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Currency:", "Euro", "Dollar", "Pound Sterling" }));
        currType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currTypeActionPerformed(evt);
            }
        });

        jLabel8.setText("Enter Price:");

        inputPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputPriceFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(currType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(slots, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(prices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115)
                        .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(156, 156, 156)
                        .addComponent(temRange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(194, 194, 194))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(slots, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(temRange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(145, 145, 145)
                .addComponent(currType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(inputPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jInternalFrame1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrame1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         
         if(this.getRuleSet()==true){
            this.systemObserver.setSlotConfigListener(true);  
         }
         else{
               ErrorDialog dialog = new ErrorDialog();
               dialog.setTitle("Configuration incomplete:");
               dialog.setMessage("You are missing some fields!");
               java.awt.EventQueue.invokeLater(new Runnable() {
                  public void run() {
                   dialog.setVisible(true);
                  }
               });
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void slotsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slotsActionPerformed
        // TODO add your handling code here:
         JComboBox cb = (JComboBox) evt.getSource();
         if(cb.getSelectedIndex()>0){
            String tmp = (String)cb.getSelectedItem().toString();
            String tmp2 [] = tmp.split(" ");
            int sel  = Integer.parseInt(tmp2[1]);
            this.setSlotID(sel);
            this.setRuleSet(0, true);
         }
    }//GEN-LAST:event_slotsActionPerformed

    private void pricesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pricesActionPerformed
        // TODO add your handling code here:
          JComboBox cb = (JComboBox) evt.getSource();
           if(cb.getSelectedIndex()>0){
            double sel  =  Double.parseDouble(cb.getSelectedItem().toString());
            this.setPrice(sel);
            this.setRuleSet(1, true);
            this.inputPrice.setEnabled(false);
           }
    }//GEN-LAST:event_pricesActionPerformed

    private void quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityActionPerformed
        // TODO add your handling code here:
        JComboBox cb = (JComboBox) evt.getSource();
        if(cb.getSelectedIndex()>0){
          int sel  = Integer.parseInt(cb.getSelectedItem().toString());
          this.setQuant(sel);
          this.setRuleSet(2, true);
        }
    }//GEN-LAST:event_quantityActionPerformed

    private void temRangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temRangeActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        
        
         JComboBox cb = (JComboBox) evt.getSource();
        
         if(cb.getSelectedIndex()>0){
            if(!cb.getSelectedItem().toString().equals("N/A")){
                String  sel  = (String) cb.getSelectedItem();
                String [] tmp2 = sel.split("-");
                double temp= Double.parseDouble(tmp2[0]) ;
                this.setTempRange(temp);
                this.setRuleSet(3, true);
            }
            else{
               this.setTempRange(0);
               this.setRuleSet(3, true);      
            }
            
          }
    }//GEN-LAST:event_temRangeActionPerformed

    private void currTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currTypeActionPerformed
        // TODO add your handling code here:
          // TODO add your handling code here:
         JComboBox cb = (JComboBox) evt.getSource();
         if(cb.getSelectedIndex()>0){
           String tmp = cb.getSelectedItem().toString();
           int sel=0;
           switch(tmp){
             case  "Euro" : sel = 1; break;
             case  "Dollar" : sel = 2; break;
             case  "Pound Sterling" : sel = 3; break;
           }
          // int sel  = Integer.parseInt();
          this.setCurrencyType(sel);
          this.setRuleSet(4, true);
         }
    }//GEN-LAST:event_currTypeActionPerformed

    private void productsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productsActionPerformed
        // TODO add your handling code here:
         JComboBox cb = (JComboBox) evt.getSource();
          if(cb.getSelectedIndex()>0){
            String  sel  = (String)cb.getSelectedItem();
            this.setProductName(sel);
            this.setRuleSet(5, true);
            this.productNameInput.setEnabled(false);
          }
    }//GEN-LAST:event_productsActionPerformed

    private void productNameInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_productNameInputFocusLost
        // TODO add your handling code here:
        String input = productNameInput.getText().toString();
        this.setProductName(input);
        this.setRuleSet(5, true);
       this.products.setEnabled(false);
    }//GEN-LAST:event_productNameInputFocusLost

    private void inputPriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputPriceFocusLost
        // TODO add your handling code here:
        double input = Double.parseDouble(inputPrice.getText().toString());
          this.setPrice(input);
          this.setRuleSet(1, true);
          this.prices.setEnabled(false);
    }//GEN-LAST:event_inputPriceFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> currType;
    private javax.swing.JTextField inputPrice;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> prices;
    private javax.swing.JTextField productNameInput;
    private javax.swing.JComboBox<String> products;
    private javax.swing.JComboBox<String> quantity;
    private javax.swing.JComboBox<String> slots;
    private javax.swing.JComboBox<String> temRange;
    // End of variables declaration//GEN-END:variables

    
}
